markdown: rdiscount
highlighter: true
permalink: /:year/:month/:day/:title.html
name: "寂兮寥兮"
markdown: redcarpet
#markdown: rdiscount

author: "Hu FU"
atom-baseurl: "http://mayitbe.net"
disqus: "mayitbe"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

